<?php
/*
 * Copyright (C) Saman beheshtian, Inc - All Rights Reserved
 * 2025.
 *
 * Author        Saman beheshtian
 * Position      Developer
 * Email         amintado@gmail.com
 * Phone         +989353466620
 * Date          4/27/25, 6:11 PM
 */

namespace Units\Users\Admin\Manage\Models;

use Modules\Basic\BaseKit\Observers\BaseObserver;
use Modules\Basic\Models\APIModel;
use Modules\FilamentManage\Models\Users;
use Units\ActLog\Admin\Observsers\ChangeModelLogObserver;
use Units\Auth\Manage\Models\UserModel;

/**
 * مدل کاربر در پنل ادمین
 * این مدل از APIModel ارث‌بری می‌کند و به جای اتصال مستقیم به دیتابیس، از طریق وب‌سرویس با پنل manage ارتباط برقرار می‌کند
 */
class User extends UserModel
{
    protected $connection="api_manage";

    protected $primaryKey = 'phone_number';
    //Prevent to convert phone_number to integer
    public $incrementing=false;
    protected $keyType = 'string';

    /**
     * نام مدل در پنل manage
     * @var string
     */
//    public $remoteModel = 'Units\Auth\Manage\Models\UserModel';

    protected static function booted()
    {
        static::observe(ChangeModelLogObserver::class);
        static::observe(BaseObserver::class);
        parent::booted(); // TODO: Change the autogenerated stub
    }

    public function get_remote_base_api():string
    {
        return env('MANAGE_BASE_MODEL_API');
    }
}
