<?php

/*
 * Copyright (C) Saman beheshtian, Inc - All Rights Reserved
 * 2025.
 *
 * Author        Saman beheshtian
 * Position      Developer
 * Email         amintado@gmail.com
 * Phone         +989353466620
 * Date          4/27/25, 5:53 PM
 */

namespace Units\Auth\Admin\Models;

use Filament\Models\Contracts\FilamentUser;
use Filament\Models\Contracts\HasName;
use Filament\Panel;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User;
use Illuminate\Notifications\Notifiable;
use Modules\Basic\BaseKit\Observers\BaseObserver;
use Spatie\Permission\Traits\HasRoles;
use Units\ActLog\Admin\Observsers\ChangeModelLogObserver;

/**
 * @property int $id
 * @property string $name
 * @property string $email
 * @property string|null $email_verified_at
 * @property string $password
 * @property string|null $remember_token
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Illuminate\Notifications\DatabaseNotificationCollection<int, \Illuminate\Notifications\DatabaseNotification> $notifications
 * @property-read int|null $notifications_count
 *
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel query()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereEmail($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereEmailVerifiedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel wherePassword($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereRememberToken($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereUpdatedAt($value)
 *
 * @property string $national_code
 * @property string $phone_number
 * @property int $status
 * @property int $validate_status check phone number and national code is for validated person
 * @property string $validate_request_at
 * @property string|null $deleted_at
 * @property string $created_by
 * @property string $deleted_by
 * @property string $deleted_reason
 * @property string $username
 * @property string $password_hash
 * @property string $deactivated_reason
 *
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereCreatedBy($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereDeletedBy($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereDeletedReason($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereNationalCode($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel wherePhoneNumber($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereStatus($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereValidateRequestAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereValidateStatus($value)
 *
 * @mixin \Eloquent
 */
class UserModel extends User implements FilamentUser, HasName
{
    protected static function booted()
    {
        static::observe(ChangeModelLogObserver::class);
        static::observe(BaseObserver::class);
        parent::booted(); // TODO: Change the autogenerated stub
    }

    use HasFactory, Notifiable;
    use HasRoles;

    protected $table = 'users';

    protected string $guard_name = 'admin';

    protected $connection = 'admin';

    protected $primaryKey = 'phone_number';

    // Prevent to convert phone_number to integer
    public $incrementing = false;

    protected $keyType = 'string';

    public function canAccessPanel(Panel $panel): bool
    {
        if ($panel->getId() === 'admin') {
            return true;
        }

        return false;
    }

    public function getFilamentName(): string
    {
        return $this->username;
    }

    protected $casts =
        [
            'phone_number' => 'string',
        ];

    /**
     * Override the morph class to ensure proper polymorphic relationship
     */
    public function getMorphClass(): string
    {
        return static::class;
    }

    /**
     * Get the value of the model's primary key.
     */
    public function getKey()
    {
        return $this->getAttribute($this->getKeyName());
    }

    public function getProfile(): array
    {
        return UserMetadata::getProfile($this->phone_number);
    }
}
