<?php
/*
 * Copyright (C) Saman beheshtian, Inc - All Rights Reserved
 * 2025.
 *
 * Author        Saman beheshtian
 * Position      Developer
 * Email         amintado@gmail.com
 * Phone         +989353466620
 * Date          4/26/25, 5:33 PM
 */

namespace Units\Auth\Admin\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Modules\Basic\BaseKit\Observers\BaseObserver;
use Units\ActLog\Admin\Observsers\ChangeModelLogObserver;

class UserMetadata extends Model
{
    protected $table = 'user_metadata';
    protected $connection = 'admin';
    protected $primaryKey = 'phone_number';
    public $incrementing = false;
    protected $keyType = 'string';

    protected $fillable = [
        'phone_number',
        'profile_image',
        'first_name',
        'last_name',
        'bio',
        'address',
        'last_login_at',
        'last_logout_at',
        'last_ip_address'
    ];

    protected $casts = [
        'last_login_at' => 'datetime',
        'last_logout_at' => 'datetime'
    ];

    protected static function booted()
    {
        static::observe(ChangeModelLogObserver::class);
        static::observe(BaseObserver::class);
        parent::booted(); // TODO: Change the autogenerated stub
    }



    public function user(): BelongsTo
    {
        return $this->belongsTo(UserModel::class, 'phone_number', 'phone_number');
    }

    public static function getProfile(string $phone_number): array
    {
        return static::where('phone_number', $phone_number)
            ->first()
            ->toArray();
    }
}
