<?php
/*
 * Copyright (C) Saman beheshtian, Inc - All Rights Reserved
 * 2025.
 *
 * Author        Saman beheshtian
 * Position      Developer
 * Email         amintado@gmail.com
 * Phone         +989353466620
 * Date          8/3/25, 8:38 PM
 */

namespace Units\Shield\My\Models;

use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Modules\Basic\BaseKit\Observers\BaseObserver;
use MongoDB\Laravel\Relations\MorphToMany;
use Units\Auth\My\Models\UserModel;
use Units\Corporates\Placed\Common\Models\CorporateModel;
use Units\Shield\My\Models\ModelHasRole;

/**
 * Role model for managing user roles with corporate context
 *
 * This model extends Spatie's Permission Role model and adds corporate-specific
 * functionality. It manages the relationship between users and roles within
 * corporate contexts using a multi-tenant approach.
 *
 * @property int $id
 * @property string $name
 * @property string $guard_name
 * @property string|null $corporate_national_code
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Illuminate\Database\Eloquent\Collection<int, \Units\Auth\My\Models\UserModel> $users
 * @property-read int|null $users_count
 * @property-read CorporateModel $corporateModel
 *
 * @method static \Illuminate\Database\Eloquent\Builder<static>|Role newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|Role newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|Role query()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|Role whereCorporateNationalCode($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|Role whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|Role whereGuardName($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|Role whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|Role whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|Role whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class Role extends \Spatie\Permission\Models\Role
{
    protected $connection = 'my';

    protected static function booted()
    {
        static::observe(BaseObserver::class);
        parent::booted(); // TODO: Change the autogenerated stub
    }

    protected $fillable = ['name', 'guard_name', 'corporate_national_code'];

    /**
     * Get the users that belong to this role.
     *
     * This relationship represents the many-to-many connection between roles and users
     * through the model_has_roles pivot table, with corporate national code as
     * additional context for multi-tenant support.
     *
     * @return BelongsToMany
     */
    public function users(): BelongsToMany
    {

        return $this->morphedByMany(UserModel::class,
            'model',
            'model_has_roles',
            'role_id',
            'model_id',
            'id',
            'id',
            'users'
        );
    }

    public function tenant()
    {
        return $this->belongsTo(CorporateModel::class, 'corporate_national_code', 'national_code');
    }

    public function corporateModel()
    {
        return $this->belongsTo(CorporateModel::class, 'corporate_national_code', 'national_code');
    }

    public function team()
    {
        return $this->belongsTo(CorporateModel::class, 'corporate_national_code', 'national_code');
    }


}
