<?php

namespace Units\Settings\Manage\Models;

use Modules\Basic\BaseKit\Model\Contracts\BaseModelContract;
use Modules\Basic\BaseKit\Observers\BaseObserver;
use Outerweb\Settings\Models\Setting;
use Units\ActLog\Common\Observers\CommonChangeModelLogObserver;

class AdminSettings extends Setting implements BaseModelContract
{

    protected static function booted()
    {
        static::observe(BaseObserver::class);
        static::observe(CommonChangeModelLogObserver::class);
        parent::booted(); // TODO: Change the autogenerated stub
    }

    public function getConnectionName()
    {
        $filament_id=filament()->getId();
        if ($filament_id==$this->original_connection()){
            $this->connection=$filament_id;
            return $this->connection;
        }else{
            if (app()->runningUnitTests()){
                $this->connection='test_'.$this->original_connection();
            }else{
                $this->connection='api_'.$this->original_connection();
            }
            return $this->connection;
        }
    }
    public function original_connection(): string
    {
        return 'admin';
    }
}
