<?php
/*
 * Copyright (C) Saman beheshtian, Inc - All Rights Reserved
 * 2025.
 *
 * Author        Saman beheshtian
 * Position      Developer
 * Email         amintado@gmail.com
 * Phone         +989353466620
 * Date          8/3/25, 8:37 PM
 */

namespace Units\Shield\Manage\Models;

use Modules\Basic\BaseKit\Observers\BaseObserver;

class Permission extends \Spatie\Permission\Models\Permission
{
    protected $connection='manage';

    protected static function booted()
    {
        static::observe(BaseObserver::class);
        parent::booted(); // TODO: Change the autogenerated stub
    }
}
