<?php

/*
 * Copyright (C) Saman beheshtian, Inc - All Rights Reserved
 * 2025.
 *
 * Author        Saman beheshtian
 * Position      Developer
 * Email         amintado@gmail.com
 * Phone         +989353466620
 * Date          4/27/25, 5:58 PM
 */

namespace Units\Auth\My\Models;

use Filament\Models\Contracts\FilamentUser;
use Filament\Models\Contracts\HasName;
use Filament\Models\Contracts\HasTenants;
use Filament\Panel;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Collection;
use Modules\Basic\BaseKit\Observers\BaseObserver;
use Modules\Basic\Helpers\Helper;
use BezhanSalleh\FilamentShield\FilamentShield;
use Spatie\Permission\Exceptions\PermissionDoesNotExist;
use Spatie\Permission\PermissionRegistrar;
use Spatie\Permission\Models\Permission as SpatiePermission;
use Spatie\Permission\Traits\HasRoles;
use Units\ActLog\My\Observers\ChangeModelLogObserver;
use Units\Auth\My\database\ActiveUserFactory;
use Units\Corporates\Placed\Common\Models\CorporateModel;
use Units\Corporates\Users\Common\Models\CorporateUsersModel;
use Units\Shield\My\Models\Role;

/**
 * @property int $id
 * @property string $national_code
 * @property string|null $phone_number
 * @property int $status
 * @property string $validate_request_at
 * @property int|null $validate_status
 * @property string $first_name
 * @property string $last_name
 * @property string $bio
 * @property string $address
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Illuminate\Notifications\DatabaseNotificationCollection<int, \Illuminate\Notifications\DatabaseNotification> $notifications
 * @property-read int|null $notifications_count
 * @property-read Role[]|Collection $roles
 * @property-read Role|Collection $firstRole
 * @property-read CorporateModel[]|Collection $corporates
 * @property-read CorporateUsersModel[]|Collection $corporateUsers
 *
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel query()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereEmail($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereEmailVerifiedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel wherePassword($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereRememberToken($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereUpdatedAt($value)
 *
 * @mixin \Eloquent
 */
class UserModel extends User implements FilamentUser, HasName, HasTenants
{
    use HasFactory, Notifiable;
    use HasRoles;

    public static string $factory = ActiveUserFactory::class;

    //    use HasRoles;
    protected $table = 'users';

    protected string $guard_name = 'my';

    protected static function booted()
    {
        static::observe(BaseObserver::class);
        static::observe(ChangeModelLogObserver::class);
        parent::booted(); // TODO: Change the autogenerated stub
    }

    public function getFilamentName(): string
    {
        return $this->phone_number;
    }

    public function canAccessPanel(Panel $panel): bool
    {
        if ($panel->getId() === 'my') {
            return true;
        }

        return false;
    }

    protected $casts =
        [
            'phone_number' => 'string',
        ];

    public function __get($key)
    {
        try {
            $result = parent::__get($key); // TODO: Change the autogenerated stub
            if (empty($result)) {
                $meta = UserMetadata::where('national_code', $this->national_code)
                    ->where('meta_key', $key)->first();
                if (!empty($meta)) {
                    return $meta->meta_value;
                } else {
                    return '';
                }
            }

            return $result;
        } catch (\Exception $e) {
            return null;
        }
    }

    /**
     * @return mixed|string|null
     */
    public function getMeta($meta_key)
    {
        return UserMetadata::where('national_code', $this->national_code)
            ->where('meta_key', $meta_key)
            ?->first()
            ?->meta_value;
    }

    public function getConnectionName()
    {
        if (env('APP_ENV') == 'testing') {
            $this->connection = 'test_my';

            return $this->connection;
        }
        $filament_id = filament()->getId();
        if ($filament_id == 'my') {
            $this->connection = $filament_id;

            return $this->connection;
        } else {
            $this->connection = 'api_my';

            return $this->connection;
        }
    }

    /**
     * Find user model using phone number.
     * Phone number will be normalize on function, then search on database
     */
    public static function findByPhone($phone_number): ?self
    {
        $phone_number = Helper::normalize_phone_number($phone_number);

        return self::where('phone_number', $phone_number)->first();
    }

    /**
     * @return \Eloquent|self
     */
    public static function findByNationalCode($user_national_code)
    {
        return self::where('national_code', $user_national_code)
            ->first();
    }

    /**
     * Override the morph class to ensure proper polymorphic relationship
     */
    public function getMorphClass(): string
    {
        return static::class;
    }

    /**
     * Get the value of the model's primary key.
     */
    public function getKey()
    {
        return (string)$this->getAttribute($this->getKeyName());
    }

    public function corporates(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(
            CorporateModel::class,
            'corporate_users',
            'user_id',
            'corporate_national_code',
            'id',
            'national_code'
        );
    }

    public function corporateUsers(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(CorporateUsersModel::class,'user_id','id');
    }

    public function getTenants(Panel $panel): array|Collection
    {
        return $this->corporates;
    }


    public function canAccessTenant($tenant): bool
    {
        return $this->corporates()->whereKey($tenant)->exists();
    }

    public function getDefaultTenant(Panel $panel)
    {
        return $this->latestTeam();
    }

    public function latestTeam(): ?CorporateModel
    {
        return $this->corporates()
            ->orderBy('corporate_users.created_at', 'desc')
            ->first();
    }



    /**
     * Grant Super Admin role for a specific tenant (corporate).
     *
     * Usage:
     * ```php
     * $user = Units\Auth\My\Models\UserModel::find(1);
     * $user->grantSuperAdminForTenant('7284242965');
     * ```
     */
    public function grantSuperAdminForTenant(string $corporateNationalCode): self
    {
        // Ensure Shield models are registered
        app(PermissionRegistrar::class)->setPermissionClass(config('permission.models.permission'));
        app(PermissionRegistrar::class)->setRoleClass(config('permission.models.role'));

        // Set team/tenant context
        setPermissionsTeamId($corporateNationalCode);

        // Ensure role exists for this tenant
        $role = FilamentShield::createRole(tenantId: $corporateNationalCode);

        // Assign to user
        $this->assignRole($role);

        return $this;
    }

    /**
     * Grant all available permissions for a specific tenant by syncing them to the Super Admin role
     * and assigning that role to the user.
     *
     * Usage:
     * ```php
     * $user = Units\Auth\My\Models\UserModel::find(1);
     * $user->grantFullAccessForTenant('7284242965');
     * ```
     */
    public function grantFullAccessForTenant(string $corporateNationalCode): self
    {
        app(PermissionRegistrar::class)->setPermissionClass(config('permission.models.permission'));
        app(PermissionRegistrar::class)->setRoleClass(config('permission.models.role'));

        setPermissionsTeamId($corporateNationalCode);

        // Create/get role for tenant
        $role = FilamentShield::createRole(tenantId: $corporateNationalCode);

        // Sync all permissions to role under this tenant
        /** @var class-string<SpatiePermission> $permissionModel */
        $permissionModel = config('permission.models.permission');
        $allPermissionIds = $permissionModel::pluck('id');
        $role->syncPermissions($allPermissionIds);

        // Assign role to user
        $this->assignRole($role);

        return $this;
    }

    /**
     * Grant full access for all of the user's tenants.
     *
     * Usage:
     * ```php
     * Units\Auth\My\Models\UserModel::query()->each(fn($u) => $u->grantFullAccessForAllTenants());
     * ```
     */
    public function grantFullAccessForAllTenants(): self
    {
        $this->corporates()->pluck('corporates.national_code')->each(function (string $tenantId) {
            $this->grantFullAccessForTenant($tenantId);
        });

        return $this;
    }

    /**
     * Get user's tenant ids (corporate national codes) as array.
     *
     * Usage:
     * ```php
     * $tenantIds = $user->getTenantIds();
     * ```
     *
     * @return array<int,string>
     */
    public function getTenantIds(): array
    {
        return $this->corporates()->pluck('corporates.national_code')->all();
    }

    /**
     * Determine if the user has the given ability in ANY of the user's tenants.
     * This method iterates through all tenant contexts and checks permissions accordingly.
     *
     * @param string|array $abilities
     * @param mixed $arguments
     * @return bool
     */
    public function canAcrossTenants(string|array $abilities, $arguments = []): bool
    {
        // Ensure permission models are properly registered
        app(\Spatie\Permission\PermissionRegistrar::class)
            ->setPermissionClass(config('permission.models.permission'));
        app(\Spatie\Permission\PermissionRegistrar::class)
            ->setRoleClass(config('permission.models.role'));

        $tenantIds = $this->getTenantIds();

        // Capture original team context to restore after checks
        $originalTeamId = function_exists('getPermissionsTeamId') ? getPermissionsTeamId() : null;

        try {
            foreach ($tenantIds as $tenantId) {
                if (function_exists('setPermissionsTeamId')) {
                    setPermissionsTeamId($tenantId);
                }

                if (is_array($abilities)) {
                    if ($this->hasAnyPermission($abilities)) {
                        return true;
                    }
                } else {
                    if ($this->hasPermissionTo($abilities)) {
                        return true;
                    }
                }
            }
        } finally {
            // Restore original team context
            if (function_exists('setPermissionsTeamId')) {
                setPermissionsTeamId($originalTeamId);
            }
        }

        return false;
    }




    /**
     * Determine if the model may perform the given permission.
     *
     * @param  string|int|\Spatie\Permission\Contracts\Permission|\BackedEnum  $permission
     * @param  string|null  $guardName
     *
     * @throws PermissionDoesNotExist
     */
    public function hasPermissionTo($permission, $guardName = null): bool
    {
        if ($this->getWildcardClass()) {
            return $this->hasWildcardPermission($permission, $guardName);
        }

        return  !(empty($this->filterPermission($permission, $guardName)));
    }

    /**
     * Get all roles for the user in the current tenant context.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function roles(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        $relation = $this->morphToMany(
            Role::class,
            'model',
            'model_has_roles',
            'model_id',
            'role_id'
        )->withPivot('corporate_national_code');

        if (function_exists('getPermissionsTeamId') && getPermissionsTeamId()) {
            $relation = $relation->wherePivot('corporate_national_code', getPermissionsTeamId());
        }
        return $relation;
    }

    /**
     * Get the first role for the user in the current tenant context.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany (returns first role through query)
     */
    public function firstRole()
    {
        $relation = $this->morphToMany(
            Role::class,
            'model',
            'model_has_roles',
            'model_id',
            'role_id'
        )->withPivot('corporate_national_code');

        if (function_exists('getPermissionsTeamId') && getPermissionsTeamId()) {
            $relation = $relation->wherePivot('corporate_national_code', getPermissionsTeamId());
        }

        return $relation->orderBy('model_has_roles.created_at', 'asc')->limit(1);
    }

    /**
     * Get all roles for the user in a specific tenant.
     *
     * @param string $tenantId The corporate national code
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function getRolesForTenant(string $tenantId)
    {
        $originalTeamId = getPermissionsTeamId();

        try {
            setPermissionsTeamId($tenantId);

            return $this->roles()->get();
        } finally {
            setPermissionsTeamId($originalTeamId);
        }
    }

    /**
     * Get the first role for the user in a specific tenant.
     *
     * @param string $tenantId The corporate national code
     * @return \Spatie\Permission\Models\Role|null
     */
    public function getFirstRoleForTenant(string $tenantId)
    {
        $originalTeamId = getPermissionsTeamId();

        try {
            setPermissionsTeamId($tenantId);

            return $this->firstRole()->first();
        } finally {
            setPermissionsTeamId($originalTeamId);
        }
    }

    /**
     * این تابع ابتدا سعی میکند نام و نام خانوادگی کاربر را واکشی کند
     *
     * در صورتی که کاربر نام و نام خانوادگی نداشته باشد٬کلمه کاربر را برمیگرداند
     * @return string
     */
    public function getFirstNameLastName():string
    {
        $profile=$this->getProfile();
        if (!empty($profile['first_name']) && !empty($profile['last_name'])){
            $first_name=$profile['first_name'];
            $last_name=$profile['last_name'];
            return $first_name.' '.$last_name;
        }
        return 'کاربر';
    }

    public function getProfile(){
        return UserMetadata::getProfile($this->national_code);
    }
}
