<?php
/*
 * Copyright (C) Saman beheshtian, Inc - All Rights Reserved
 * 2025.
 *
 * Author        Saman beheshtian
 * Position      Developer
 * Email         amintado@gmail.com
 * Phone         +989353466620
 * Date          4/27/25, 5:57 PM
 */

namespace Units\Auth\My\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;
use Modules\Basic\BaseKit\Model\BaseSqlModel;
use Modules\Basic\BaseKit\Observers\BaseObserver;
use Units\ActLog\My\Observers\ChangeModelLogObserver;
use Units\Auth\My\Models\UserModel;

/**
 * @property string $id
 * @property string $national_code
 * @property string $meta_key
 * @property string $meta_value
 * @property string $meta_extra
 * @property string $created_at
 * @property string $deleted_at
 * @property string $created_by
 * @property string $deleted_by
 * @property string $deleted_reason
 */
class UserMetadata extends BaseSqlModel
{
    use SoftDeletes;

    protected $table = 'user_meta';

    protected $primaryKey = 'id';
    public $incrementing = false;
    protected $keyType = 'string';

    protected $fillable = [
        'national_code',
        'meta_key',
        'meta_value',
        'updated_at',
        'updated_by'
    ];


    protected static function booted()
    {
        static::observe(ChangeModelLogObserver::class);
        static::observe(BaseObserver::class);
        parent::booted(); // TODO: Change the autogenerated stub
    }


    public function user(): BelongsTo
    {
        return $this->belongsTo(UserModel::class, 'phone_number', 'phone_number');
    }

    public function original_connection(): string
    {
        return 'my';
    }

    public static function getProfile(string $national_code): array
    {
        if(cache()->has('profile_'.$national_code)){
            return cache()->get('profile_'.$national_code);
        }else{
            $out= static::where('national_code', $national_code)
                ->whereNull('deleted_at')
                ->pluck('meta_value', 'meta_key')
                ->toArray();
            cache()->set('profile_'.$national_code, $out,120);
            return $out;
        }
    }

    /**
     * به‌روزرسانی اطلاعات پروفایل کاربر
     *
     * @param string $national_code
     * @param array $data
     * @return $this
     */
    public static function updateProfile(string $national_code, array $data): bool
    {
        foreach ($data as $attribute => $value) {
            static::add_meta_key($attribute, (string)$value, $national_code);
        }
        if(cache()->has('profile_'.$national_code)){
            cache()->delete('profile_'.$national_code);
        }
        return true;
    }


    public static function add_meta_key(string $meta_key, string|null $meta_value, string $national_code = '')
    {
        if (empty($national_code)) {
            $national_code = auth()?->user()?->national_code;
        }
        $user_meta = static::where('national_code', $national_code)
            ->where('meta_key', $meta_key)->first();

        if (!empty($user_meta)) {
            $user_meta->meta_value = $meta_value;
            if ($user_meta->isDirty()) {
                $user_meta->delete();
            } else {
                return null;
            }
        }
        return static::create([
            'id' => Str::uuid(),
            'national_code' => $national_code,
            'meta_key' => $meta_key,
            'meta_value' => (string)$meta_value,
        ]);
    }


}
