<?php

namespace Units\StateCity\Common\Models;

use Illuminate\Database\Eloquent\Model;
use Modules\Basic\BaseKit\Observers\BaseObserver;
use Units\ActLog\Common\Observers\CommonChangeModelLogObserver;

class Province extends Model
{
    protected $guarded=[];
    protected $connection='my';

    protected static function booted()
    {
        static::observe(BaseObserver::class);
        static::observe(CommonChangeModelLogObserver::class);
        parent::booted(); // TODO: Change the autogenerated stub
    }

}
