<?php
/*
 * Copyright (C) Saman beheshtian, Inc - All Rights Reserved
 * 2025.
 *
 * Author        Saman beheshtian
 * Position      Developer
 * Email         amintado@gmail.com
 * Phone         +989353466620
 * Date          4/27/25, 5:57 PM
 */

namespace Units\Auth\Manage\Models;

use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Str;
use Modules\Basic\BaseKit\Model\BaseModel;
use Modules\Basic\BaseKit\Observers\BaseObserver;
use Modules\FilamentManage\Models\ManageBaseModel;
use Units\ActLog\Manage\Observers\ChangeModelLogObserver;

class UserMetadata extends BaseModel
{
    protected $table = 'user_metadata';
//    protected $connection = 'admin';
    protected $primaryKey = 'phone_number';
    public $incrementing = false;
    protected $keyType = 'string';

    protected $fillable = [
        'phone_number',
        'meta_key',
        'meta_value',
        'updated_at',
        'updated_by'
    ];


    protected static function booted()
    {
        static::observe(ChangeModelLogObserver::class);
        static::observe(BaseObserver::class);
        parent::booted(); // TODO: Change the autogenerated stub
    }



    public function user(): BelongsTo
    {
        return $this->belongsTo(UserModel::class, 'phone_number', 'phone_number');
    }

    public function original_connection(): string
    {
        return 'manage';
    }

    public static function getProfile(string $phone_number): array
    {
        return static::where('phone_number', $phone_number)
            ->pluck('meta_value', 'meta_key')
            ->toArray();
    }


    /**
     * به‌روزرسانی اطلاعات پروفایل کاربر
     *
     * @param string $phone_number
     * @param array $data
     * @return $this
     */
    public static function updateProfile(string $phone_number, array $data): bool
    {
        foreach ($data as $attribute => $value) {
            static::add_meta_key($attribute, (string)$value, $phone_number);
        }
        return true;
    }
    public static function add_meta_key(string $meta_key, string|null $meta_value, string $phone_number = '')
    {
        if (empty($phone_number)) {
            $phone_number = auth()?->user()?->phone_number;
        }
        $user_meta = static::where('phone_number', $phone_number)
            ->where('meta_key', $meta_key)->first();

        if (!empty($user_meta)) {
            $user_meta->meta_value = $meta_value;
            if ($user_meta->isDirty()) {
                $user_meta->delete();
            } else {
                return null;
            }
        }
        return static::create([
            'id' => Str::uuid(),
            'phone_number' => $phone_number,
            'meta_key' => $meta_key,
            'meta_value' => (string)$meta_value,
        ]);
    }
}
