<?php

/*
 * Copyright (C) Saman beheshtian, Inc - All Rights Reserved
 * 2025.
 *
 * Author        Saman beheshtian
 * Position      Developer
 * Email         amintado@gmail.com
 * Phone         +989353466620
 * Date          4/27/25, 5:57 PM
 */

namespace Units\Auth\Manage\Models;

use Filament\Models\Contracts\FilamentUser;
use Filament\Models\Contracts\HasName;
use Filament\Panel;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Foundation\Auth\User;
use Illuminate\Notifications\Notifiable;
use Modules\Basic\BaseKit\Observers\BaseObserver;
use Spatie\Permission\PermissionRegistrar;
use Spatie\Permission\Traits\HasRoles;
use Units\ActLog\Manage\Observers\ChangeModelLogObserver;
use Units\Shield\Common\ShieldHelper;
use Units\Shield\Manage\Models\Role;

/**
 * @property int $id
 * @property int $status
 * @property int $validate_status check phone number and national code is for validated person
 * @property-read int|null $notifications_count
 * @property string $email
 * @property string|null $email_verified_at
 * @property string $password
 * @property string|null $remember_token
 * @property string $national_code
 * @property string $phone_number
 * @property string $first_name
 * @property string $last_name
 * @property string $validate_request_at
 * @property string|null $deleted_at
 * @property string $created_by
 * @property string $deleted_by
 * @property string $deleted_reason
 * @property string $username
 * @property string $password_hash
 * @property string $deactivated_reason
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property string $name
 * @property-read \Illuminate\Notifications\DatabaseNotificationCollection<int, \Illuminate\Notifications\DatabaseNotification> $notifications
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel query()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereEmail($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereEmailVerifiedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel wherePassword($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereRememberToken($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereCreatedBy($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereDeletedBy($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereDeletedReason($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereNationalCode($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel wherePhoneNumber($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereStatus($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereValidateRequestAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|UserModel whereValidateStatus($value)
 * @mixin \Eloquent
 */
class UserModel extends User implements FilamentUser, HasName
{
    protected static function booted()
    {
        static::observe(ChangeModelLogObserver::class);
        static::observe(BaseObserver::class);
        parent::booted(); // TODO: Change the autogenerated stub
    }

    use HasFactory, Notifiable;
    use HasRoles;

    protected $table = 'users';

    protected $connection = 'manage';

    protected string $guard_name = 'manage';

    protected $primaryKey = 'phone_number';

    // Prevent to convert phone_number to integer
    public $incrementing = false;

    protected $keyType = 'string';

    public function canAccessPanel(Panel $panel): bool
    {
        if ($panel->getId() === 'manage') {
            return true;
        }

        return false;
    }

    public function getFilamentName(): string
    {
        return $this->username;
    }

    public function getRoleClass(): string
    {
        if (!$this->roleClass) {
            $this->roleClass = Role::class;
        }

        return $this->roleClass;
    }

    protected $casts =
        [
            'phone_number' => 'string',
        ];

    /**
     * Override the morph class to ensure proper polymorphic relationship
     */
    public function getMorphClass(): string
    {
        return static::class;
    }

    /**
     * Get the value of the model's primary key.
     */
    public function getKey()
    {
        return $this->getAttribute($this->getKeyName());
    }

    /**
     * Get users who have a specific permission
     *
     * @param string $permissionName The name of the permission to check for
     * @param int|null $limit The maximum number of users to return (null for no limit)
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public static function getUsersWithPermission(
        string $permissionName,
        ?int $limit = null
    ): \Illuminate\Database\Eloquent\Collection {
        $query = static::whereHas('permissions', function ($query) use ($permissionName) {
            $query->where('name', $permissionName);
        })
            ->orWhereHas('roles.permissions', function ($query) use ($permissionName) {
                $query->where('name', $permissionName);
            });

        if ($limit !== null) {
            $query->limit($limit);
        }

        return $query->get();
    }

    public function permissions(): BelongsToMany
    {
        $pivotPermission=app(PermissionRegistrar::class)->pivotPermission;
        $relation = $this->morphToMany(
            ShieldHelper::getConfig('manage', 'permission.models.permission'),
            'model',
            ShieldHelper::getConfig('manage', 'permission.table_names.model_has_permissions'),
            ShieldHelper::getConfig('manage', 'permission.column_names.model_morph_key'),
            $pivotPermission
        );


        return $relation;
    }

    /**
     * A model may have multiple roles.
     */
    public function roles(): BelongsToMany
    {
        $pivot = app(PermissionRegistrar::class)->pivotRole;
        $relation = $this->morphToMany(
            ShieldHelper::getConfig('manage', 'permission.models.role'),
            'model',
            ShieldHelper::getConfig('manage', 'permission.table_names.model_has_roles'),
            ShieldHelper::getConfig('manage', 'permission.column_names.model_morph_key'),
            $pivot
        );


        return $relation;
    }

    public function __get($key)
    {
        try {
            $result = parent::__get($key); // TODO: Change the autogenerated stub
            if (empty($result)) {
                $meta = UserMetadata::where('phone_number', $this->phone_number)
                    ->where('meta_key', $key)->first();
                if (!empty($meta)) {
                    return $meta->meta_value;
                } else {
                    return '';
                }
            }

            return $result;
        } catch (\Exception $e) {
            return null;
        }
    }
    /**
     * @return mixed|string|null
     */
    public function getMeta($meta_key)
    {
        return \Units\Auth\Manage\Models\UserMetadata::where('phone_number', $this->phone_number)
            ->where('meta_key', $meta_key)
            ?->first()
            ?->meta_value;
    }

    /**
     * این تابع ابتدا سعی میکند نام و نام خانوادگی کاربر را واکشی کند
     *
     * در صورتی که کاربر نام و نام خانوادگی نداشته باشد٬کلمه کاربر را برمیگرداند
     * @return string
     */
    public function getFirstNameLastName():string
    {
        $first_name=$this->first_name;
        $last_name=$this->last_name;
        if (!empty($first_name) || !empty($last_name)){
            return $first_name.' '.$last_name;
        }else{
            return $this->phone_number;
        }
    }

    public function getFilamentAvatarUrl(): ?string
    {
        return null;
    }

    public function getProfile(): array
    {
        return UserMetadata::getProfile($this->phone_number);
    }
}
