<?php

namespace Modules\Basic\Models;

use Filament\Facades\Filament;
use Illuminate\Database\Eloquent\Scope;
use Illuminate\Database\Query\Builder as QueryBuilder;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Pagination\LengthAwarePaginator;

/**
 * کلاس سازنده کوئری‌های API
 * این کلاس برای ساخت و اجرای کوئری‌های API استفاده می‌شود
 * @property APIModel $model
 */
class APIQueryBuilder extends Builder
{
    /**
     * مدل مربوطه
     * @var APIModel
     */
    protected $model;
    protected $query = APIQuery::class;
    /**
     * پارامترهای کوئری
     * @var array
     */
    protected $queryParams = [];

    public function __construct(QueryBuilder $query)
    {
        parent::__construct($query);
    }

    public function toBase()
    {
        return parent::toBase(); // TODO: Change the autogenerated stub
    }

    /**
     * اضافه کردن شرط where
     * @param array|\Closure|\Illuminate\Contracts\Database\Query\Expression|string $column
     * @param null $operator
     * @param null $value
     * @param string $boolean
     * @return $this
     */
    public function where($column, $operator = null, $value = null, $boolean = 'and')
    {
        if (func_num_args() === 2) {
            $value = $operator;
            $operator = '=';
        }

        $this->queryParams['filters'][] = [
            'column' => $column,
            'operator' => $operator,
            'value' => $value
        ];

        return $this;
    }

    /**
     * مرتب‌سازی نتایج
     * @param string $column
     * @param string $direction
     * @return $this
     */
    public function orderBy($column, $direction = 'asc')
    {
        $this->queryParams['order_by'] = [
            'column' => $column,
            'direction' => $direction
        ];

        return $this;
    }

    /**
     * محدود کردن تعداد نتایج
     * @param int $limit
     * @return $this
     */
    public function limit($limit)
    {
        $this->queryParams['limit'] = $limit;
        return $this;
    }

    /**
     * تنظیم offset
     * @param int $offset
     * @return $this
     */
    public function offset($offset)
    {
        $this->queryParams['offset'] = $offset;
        return $this;
    }

    /**
     * دریافت اولین نتیجه
     * @param array|string $columns
     * @return Model|null
     */
    public function first($columns = ['*'])
    {
        $this->limit(1);
        $results = $this->get($columns);
        return $results->first();
    }

    /**
     * دریافت اولین نتیجه یا خطا
     * @param array|string $columns
     * @return Model
     * @throws \Illuminate\Database\Eloquent\ModelNotFoundException
     */
    public function firstOrFail($columns = ['*'])
    {
        $result = $this->first($columns);
        if (!$result) {
            throw new \Illuminate\Database\Eloquent\ModelNotFoundException();
        }
        return $result;
    }

    /**
     * دریافت مدل با شناسه
     * @param mixed $id
     * @param array|string $columns
     * @return Model|null
     */
    public function find($id, $columns = ['*'])
    {
        $this->queryParams['data'] = ['id' => $id];
        $response = $this->sendRequest('find', $columns);
        $model = $this->model->newInstance($response);
        $model->syncOriginal();
        return $response ? $model : null;
    }

    /**
     * دریافت مدل با شناسه یا خطا
     * @param mixed $id
     * @param array|string $columns
     * @return Model
     * @throws \Illuminate\Database\Eloquent\ModelNotFoundException
     */
    public function findOrFail($id, $columns = ['*'])
    {
        $result = $this->find($id, $columns);
        if (!$result) {
            throw new \Illuminate\Database\Eloquent\ModelNotFoundException();
        }
        return $result;
    }

    /**
     * دریافت تمام نتایج
     * @param array|string $columns
     * @return Collection
     */
    public function get($columns = ['*'])
    {
        $response = $this->sendRequest('get', $columns);
        return $this->response_to_collection($response, true);
    }

    /**
     * شمارش تعداد نتایج
     * @param string $columns
     * @return int
     */
    public function count($columns = '*')
    {
        return $this->sendRequest('count');
    }

    /**
     * صفحه‌بندی نتایج
     * @param int|null $perPage
     * @param array|string $columns
     * @param string $pageName
     * @param int|null $page
     * @param \Closure|int|null $total
     * @return LengthAwarePaginator
     */
    public function paginate($perPage = null, $columns = ['*'], $pageName = 'page', $page = null, $total = null)
    {
        $this->queryParams['data'] = [
            'per_page' => $perPage,
            'page' => $page
        ];
        $response = $this->sendRequest('paginate', $columns);

        $collection = $this->response_to_collection($response['data']);
        return new LengthAwarePaginator(
            $collection,
            $response['total'],
            $response['per_page'],
            $response['current_page'],
            ['path' => $response['path']]
        );
    }

    protected function response_to_collection(array $response, $sync_original = false): Collection
    {
        $models = [];
        foreach ($response as $item) {
            /**
             * @var $model APIModel
             */
            $model = new $this->model();
            $model->fill($item);
            $model->exists = true;
            $model->wasRecentlyCreated = true;
            if ($sync_original) {
                $model->syncOriginal();
            }
//            $model->setKeyName(array_keys($item)[0]);
//            $model->setKeyType(gettype($item[array_keys($item)[0]]));
            $models[] = $model;
        }

        return Collection::make($models);
    }


//    /**
//     * ایجاد مدل جدید
//     * @param array $attributes
//     * @return Model
//     */
//    public function create(array $attributes = [])
//    {
//        $this->queryParams['data'] = $attributes;
//        $response = $this->sendRequest('create');
//        return $this->model->newInstance($response);
//    }


    public function insert(array $values)
    {
        // Since every insert gets treated like a batch insert, we will make sure the
        // bindings are structured in a way that is convenient when building these
        // inserts statements by verifying these elements are actually an array.
        if (empty($values)) {
            return true;
        }

        if (!is_array(reset($values))) {
            $values = [$values];
        }

        // Here, we will sort the insert keys for every record so that each insert is
        // in the same order for the record. We need to make sure this is the case
        // so there are not any errors or problems when inserting these records.
        else {
            foreach ($values as $key => $value) {
                ksort($value);

                $values[$key] = $value;
            }
        }

        $this->applyBeforeQueryCallbacks();

        // Finally, we will run this query against the database connection and return
        // the results. We will need to also flatten these bindings before running
        // the query so they are all in one huge, flattened array for execution.
        $data = $this->sendRequest('insert');
        if ($data) {

            return true;
        }
        return false;
    }


    /**
     * به‌روزرسانی مدل
     * @param array $attributes
     * @return bool
     */
    public function update(array $attributes = [])
    {
        $this->queryParams['data'] = $attributes;
        $response = $this->sendRequest('update');
        return $response['success'] ?? false;
    }

    /**
     * حذف مدل
     * @return bool
     */
    public function delete()
    {
        $response = $this->sendRequest('delete');
        return $response['success'] ?? false;
    }

    /**
     * حذف دائمی مدل
     * @return bool
     */
    public function forceDelete()
    {
        $response = $this->sendRequest('forceDelete');
        return $response['success'] ?? false;
    }

    /**
     * بازیابی مدل حذف شده
     * @return bool
     */
    public function restore()
    {
        $response = $this->sendRequest('restore');
        return $response['success'] ?? false;
    }

    /**
     * به‌روزرسانی یا ایجاد مدل
     * @param array $attributes
     * @param array $values
     * @return Model
     */
    public function updateOrCreate(array $attributes, array $values = [])
    {
        $this->queryParams['data'] = [
            'attributes' => $attributes,
            'values' => $values
        ];
        $response = $this->sendRequest('updateOrCreate');
        return $this->model->newInstance($response);
    }

    /**
     * دریافت اولین مدل یا ایجاد مدل جدید
     * @param array $attributes
     * @param array $values
     * @return Model
     */
    public function firstOrCreate(array $attributes = [], array $values = [])
    {
        $this->queryParams['data'] = [
            'attributes' => $attributes,
            'values' => $values
        ];
        $response = $this->sendRequest('firstOrCreate');
        return $this->model->newInstance($response);
    }

    /**
     * دریافت اولین مدل یا ایجاد نمونه جدید
     * @param array $attributes
     * @param array $values
     * @return Model
     */
    public function firstOrNew(array $attributes = [], array $values = [])
    {
        $this->queryParams['data'] = [
            'attributes' => $attributes,
            'values' => $values
        ];
        $response = $this->sendRequest('firstOrNew');
        return $this->model->newInstance($response);
    }


    /**
     * Get the count of the total records for the paginator.
     *
     * @param array $columns
     * @return int
     */
    public function getCountForPagination($columns = ['*'])
    {
        $results = $this->runPaginationCountQuery($columns);

        // Once we have run the pagination count query, we will get the resulting count and
        // take into account what type of query it was. When there is a group by we will
        // just return the count of the entire results set since that will be correct.
        if (!isset($results[0])) {
            return 0;
        } elseif (is_object($results[0])) {
            return (int)$results[0]->aggregate;
        }

        return (int)array_change_key_case((array)$results[0])['aggregate'];
    }


    /**
     * ارسال درخواست به API
     * @param string $action
     * @param array|string $columns
     * @return array|null
     */
    protected function sendRequest($action, $columns = ['*'])
    {
        $data = $this->queryParams['data'] ?? [];
        if ($action == 'insert') {
            $data = $this->model->toArray();
        }
        if ($action == 'update') {
            $data = [
                'old' => $this->model->getAttributes(),
                'dirty' => $this->model->getDirty()
            ];
        }
        $url = $this->model->get_remote_base_api() . "/models";
        $this->queryParams['columns'] = $columns;
        $data = [
            'model_class' => $this->model->remoteModel,
            'action' => $action,
            'data' => $data,
            'filters' => $this->queryParams['filters'] ?? [],
            'order_by' => $this->queryParams['order_by'] ?? null,
            'limit' => $this->queryParams['limit'] ?? null,
            'offset' => $this->queryParams['offset'] ?? null,
            'columns' => $columns,
            'actor_number' => Filament::getCurrentPanel()->getId().'_'.Filament::auth()->user()->phone_number,
            'extra' => [
                'pk' => $this->model->getKeyName()
            ]

        ];
        $response = Http::post($url, $data);

        if ($response->successful()) {
            return $data = $response->json()['data'];
        }
        Log::error("Remote model call Error Tracing", [$response->json()['trace']]);
        throw new \Exception("Remote model Response:  " . $response->json()['error'], $response->getStatusCode());
        return null;
    }

    /**
     * تولید کلید کش
     * @return string
     */
    protected function generateCacheKey()
    {
        return "api_query_{$this->model->getTable()}_" . md5(json_encode($this->queryParams));
    }
}
