<?php

/*
 * Copyright (C) Saman beheshtian, Inc - All Rights Reserved
 * 2025.
 *
 * Author        Saman beheshtian
 * Position      Developer
 * Email         amintado@gmail.com
 * Phone         +989353466620
 * Date          4/8/25, 7:57 PM
 */

namespace Units\Users\Manage\My\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Modules\Basic\BaseKit\Observers\BaseObserver;

/**
 * @property string $national_code
 * @property string $meta_key
 * @property string $meta_value
 * @property string|null $meta_extra
 * @property \Carbon\Carbon|null $created_at
 * @property \Carbon\Carbon|null $deleted_at
 * @property string $created_by
 * @property string $deleted_by
 * @property string $deleted_reason
 */
class UserMeta extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * The connection name for the model.
     *
     * @var string
     */
    protected $connection = 'my';

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'user_meta';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = false;

    /**
     * The primary key for the model.
     *
     * @var array
     */
    protected $primaryKey = ['national_code', 'meta_key'];

    /**
     * Indicates if the IDs are auto-incrementing.
     *
     * @var bool
     */
    public $incrementing = false;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'national_code',
        'meta_key',
        'meta_value',
        'meta_extra',
        'created_by',
        'deleted_by',
        'deleted_reason',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'created_at' => 'datetime',
        'deleted_at' => 'datetime',
    ];

    protected static function booted()
    {
        static::observe(BaseObserver::class);
        parent::booted(); // TODO: Change the autogenerated stub
    }


    /**
     * Get the user that owns the meta data.
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class, 'national_code', 'national_code');
    }
}
