<?php

/*
 * Copyright (C) Saman beheshtian, Inc - All Rights Reserved
 * 2025.
 *
 * Author        Saman beheshtian
 * Position      Developer
 * Email         amintado@gmail.com
 * Phone         +989353466620
 * Date          4/8/25, 7:57 PM
 */

namespace Units\Users\Manage\My\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Modules\Basic\BaseKit\Observers\BaseObserver;
use Units\Auth\My\Models\UserModel;
use Units\Users\Manage\My\Enums\UserStatusEnum;
use Units\Users\Manage\My\Enums\ValidateStatusEnum;

/**
 * @property int $id
 * @property string $national_code
 * @property string $phone_number
 * @property int $status
 * @property int $validate_status
 * @property \Carbon\Carbon|null $validate_request_at
 * @property \Carbon\Carbon|null $created_at
 * @property \Carbon\Carbon|null $updated_at
 * @property \Carbon\Carbon|null $deleted_at
 * @property string $created_by
 * @property string $deleted_by
 * @property string $deleted_reason
 */
class User extends UserModel
{
    use HasFactory, SoftDeletes;

    /**
     * The connection name for the model.
     *
     * @var string
     */
    protected $connection = 'my';

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'national_code',
        'phone_number',
        'status',
        'validate_status',
        'validate_request_at',
        'created_by',
        'deleted_by',
        'deleted_reason',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'status' => 'integer',
        'validate_status' => 'integer',
        'validate_request_at' => 'datetime',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'deleted_at' => 'datetime',
    ];


    protected static function booted()
    {
        static::observe(BaseObserver::class);
        parent::booted(); // TODO: Change the autogenerated stub
    }

    /**
     * Get the meta data for the user.
     */
    public function meta(): HasMany
    {
        return $this->hasMany(UserMeta::class, 'national_code', 'national_code');
    }

    /**
     * Activate the user.
     */
    public function activate(): void
    {
        $this->status = UserStatusEnum::ACTIVE->value;
        $this->save();
    }

    /**
     * Deactivate the user.
     */
    public function deactivate(): void
    {
        $this->status = UserStatusEnum::INACTIVE->value;
        $this->save();
    }
}
